version: "3.9"

services:
  api:
    build: .
    container_name: portfolio-bot-api
    env_file:
      - .env
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 5000
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/portfolio_bot
      REDIS_URL: redis://redis:6379/0
      SESSION_TTL_SECONDS: 3600
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - devnet

  postgres:
    image: postgres:16
    container_name: portfolio-bot-postgres
    environment:
      POSTGRES_DB: portfolio_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devnet

  redis:
    image: redis:7
    container_name: portfolio-bot-redis
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devnet

volumes:
  postgres_data:

networks:
  devnet:
    external: true
